#!/usr/bin/env node

// This script is used to generate the list of supported directives for documentation.

const camelize = require('camelize')

Object.keys(require('../lib/config').directives)
  .sort()
  .forEach((directive) => {
    console.log([
      '* `', directive, '` ',
      'or `', camelize(directive), '`'
    ].join(''))
  })
